---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flax
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flax-ds
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: flaxd
    spec:
      serviceAccountName: flax
      containers:
        - name: flaxd
          image: johnlin/flaxd
          volumeMounts:
            - name: ovsdbsock
              mountPath: /var/run/openvswitch/db.sock
            - name: netconf
              mountPath: /etc/cni/net.d/linen.conflist
      volumes:
        - hostPath:
           path: /var/run/openvswitch/db.sock
          name: ovsdbsock
        - hostPath:
           path: /etc/cni/net.d/linen.conflist
          name: netconf